# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxLogin
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxKeyboard'
  
  target 'RxLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxLoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
